-- MySQL Script generated by MySQL Workbench
-- Wed Mar 10 12:16:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pm2-project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pm2-project` ;

-- -----------------------------------------------------
-- Schema pm2-project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pm2-project` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema pm2-portfolio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pm2-portfolio` ;

-- -----------------------------------------------------
-- Schema pm2-portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pm2-portfolio` DEFAULT CHARACTER SET utf8 ;
USE `pm2-project` ;

-- -----------------------------------------------------
-- Table `pm2-portfolio`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-portfolio`.`projects` ;

CREATE TABLE IF NOT EXISTS `pm2-portfolio`.`projects` (
  `id_project` VARCHAR(32) NOT NULL DEFAULT '(replace(uuid(), "-", ""))',
  `code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id_project`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-project`.`phases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-project`.`phases` ;

CREATE TABLE IF NOT EXISTS `pm2-project`.`phases` (
  `id_phase` INT NOT NULL,
  `code` VARCHAR(150) NOT NULL,
  `name` VARCHAR(250) NOT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id_phase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-project`.`projects_phases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-project`.`projects_phases` ;

CREATE TABLE IF NOT EXISTS `pm2-project`.`projects_phases` (
  `id_project` VARCHAR(32) NOT NULL,
  `id_phase` INT NOT NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `duration` INT NULL COMMENT 'in days',
  PRIMARY KEY (`id_project`, `id_phase`),
  INDEX `fk_projects_phases_phases_idx` (`id_phase` ASC) VISIBLE,
  CONSTRAINT `fk_projects_phases_projects`
    FOREIGN KEY (`id_project`)
    REFERENCES `pm2-portfolio`.`projects` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_phases_phases`
    FOREIGN KEY (`id_phase`)
    REFERENCES `pm2-project`.`phases` (`id_phase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-project`.`stakeholders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-project`.`stakeholders` ;

CREATE TABLE IF NOT EXISTS `pm2-project`.`stakeholders` (
  `id_stakeholder` VARCHAR(32) NOT NULL DEFAULT '(replace(uuid(), "-", ""))' COMMENT 'Strakeholders are people (or groups) who can affect or be affected by the activities carried out during a project’s lifecycle and/or by the project’s output(s) and outcome(s). A stakeholder can exert influence over the project and its deliverables.',
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `is_company` TINYINT(1) NULL DEFAULT 0,
  `stakeholderscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_stakeholder`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-project`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-project`.`teams` ;

CREATE TABLE IF NOT EXISTS `pm2-project`.`teams` (
  `id_team` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `code` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_team`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-project`.`impacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-project`.`impacts` ;

CREATE TABLE IF NOT EXISTS `pm2-project`.`impacts` (
  `id_impact` INT NOT NULL,
  `value` VARCHAR(1) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_impact`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-project`.`stakeholders_teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-project`.`stakeholders_teams` ;

CREATE TABLE IF NOT EXISTS `pm2-project`.`stakeholders_teams` (
  `id_stakeholder` VARCHAR(32) NOT NULL,
  `id_team` INT NOT NULL,
  `id_impact` INT NOT NULL,
  PRIMARY KEY (`id_stakeholder`, `id_team`, `id_impact`),
  INDEX `fk_stakeholders_teams_teams_idx` (`id_team` ASC) VISIBLE,
  INDEX `fk_stakeholders_teams_impacts_idx` (`id_impact` ASC) VISIBLE,
  CONSTRAINT `fk_stakeholders_teams_stakeholders`
    FOREIGN KEY (`id_stakeholder`)
    REFERENCES `pm2-project`.`stakeholders` (`id_stakeholder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stakeholders_teams_teams`
    FOREIGN KEY (`id_team`)
    REFERENCES `pm2-project`.`teams` (`id_team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stakeholders_teams_impacts`
    FOREIGN KEY (`id_impact`)
    REFERENCES `pm2-project`.`impacts` (`id_impact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-portfolio`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-portfolio`.`roles` ;

CREATE TABLE IF NOT EXISTS `pm2-portfolio`.`roles` (
  `id_role` VARCHAR(5) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `R/P` VARCHAR(10) NOT NULL,
  `G/I` VARCHAR(10) NOT NULL,
  `role_type` VARCHAR(30) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `PSC_participation` VARCHAR(10) NOT NULL,
  `classification` VARCHAR(45) NULL,
  `RASCI` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-project`.`stakeholders_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-project`.`stakeholders_roles` ;

CREATE TABLE IF NOT EXISTS `pm2-project`.`stakeholders_roles` (
  `id_stakeholder` VARCHAR(32) NOT NULL,
  `id_role` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_stakeholder`, `id_role`),
  INDEX `fk_stakeholders_roles_roles_idx` (`id_role` ASC) VISIBLE,
  CONSTRAINT `fk_stakeholders_roles_stakeholders`
    FOREIGN KEY (`id_stakeholder`)
    REFERENCES `pm2-project`.`stakeholders` (`id_stakeholder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stakeholders_roles_roles`
    FOREIGN KEY (`id_role`)
    REFERENCES `pm2-portfolio`.`roles` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-project`.`artefacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-project`.`artefacts` ;

CREATE TABLE IF NOT EXISTS `pm2-project`.`artefacts` (
  `id_artefact` INT NOT NULL,
  `code` VARCHAR(100) NULL,
  `name` VARCHAR(150) NULL,
  `id_phase` INT NOT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id_artefact`),
  INDEX `fk_artefacts_phases_idx` (`id_phase` ASC) VISIBLE,
  CONSTRAINT `fk_artefacts_phases`
    FOREIGN KEY (`id_phase`)
    REFERENCES `pm2-project`.`phases` (`id_phase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-project`.`rasci_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-project`.`rasci_codes` ;

CREATE TABLE IF NOT EXISTS `pm2-project`.`rasci_codes` (
  `rasci` VARCHAR(5) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`rasci`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-project`.`rasci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-project`.`rasci` ;

CREATE TABLE IF NOT EXISTS `pm2-project`.`rasci` (
  `id_artefact` INT NOT NULL,
  `id_role` VARCHAR(5) NOT NULL,
  `rasci` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_artefact`, `id_role`, `rasci`),
  INDEX `fk_rasci_roles_idx` (`id_role` ASC) VISIBLE,
  INDEX `fk_rasci_rasci_codes_idx` (`rasci` ASC) VISIBLE,
  CONSTRAINT `fk_rasci_artefacts`
    FOREIGN KEY (`id_artefact`)
    REFERENCES `pm2-project`.`artefacts` (`id_artefact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rasci_roles`
    FOREIGN KEY (`id_role`)
    REFERENCES `pm2-portfolio`.`roles` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rasci_rasci_codes`
    FOREIGN KEY (`rasci`)
    REFERENCES `pm2-project`.`rasci_codes` (`rasci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `pm2-portfolio` ;

-- -----------------------------------------------------
-- Table `pm2-portfolio`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-portfolio`.`users` ;

CREATE TABLE IF NOT EXISTS `pm2-portfolio`.`users` (
  `id_user` VARCHAR(32) NOT NULL DEFAULT '(replace(uuid(), "-", ""))',
  `user_name` VARCHAR(16) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-portfolio`.`projects_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-portfolio`.`projects_users` ;

CREATE TABLE IF NOT EXISTS `pm2-portfolio`.`projects_users` (
  `id_project` VARCHAR(32) NOT NULL,
  `id_user` VARCHAR(32) NOT NULL,
  `id_role` VARCHAR(5) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_project`, `id_user`, `id_role`),
  INDEX `fk_projects_users_users_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_projects_users_permissions_idx` (`id_role` ASC) VISIBLE,
  CONSTRAINT `fk_projects_users_projects`
    FOREIGN KEY (`id_project`)
    REFERENCES `pm2-portfolio`.`projects` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_users_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `pm2-portfolio`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_users_roles`
    FOREIGN KEY (`id_role`)
    REFERENCES `pm2-portfolio`.`roles` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-portfolio`.`users_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-portfolio`.`users_info` ;

CREATE TABLE IF NOT EXISTS `pm2-portfolio`.`users_info` (
  `id_user` VARCHAR(32) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `zip_code` VARCHAR(10) NULL DEFAULT NULL,
  `address` VARCHAR(150) NULL DEFAULT NULL,
  `phone_number` VARCHAR(12) NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`, `start_date`),
  CONSTRAINT `fk_users_info_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `pm2-portfolio`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-portfolio`.`user_credentials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-portfolio`.`user_credentials` ;

CREATE TABLE IF NOT EXISTS `pm2-portfolio`.`user_credentials` (
  `id_user` VARCHAR(32) NOT NULL,
  `date` DATE NOT NULL,
  `user_name` VARCHAR(16) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`),
  CONSTRAINT `fk_users_info_users0`
    FOREIGN KEY (`id_user`)
    REFERENCES `pm2-portfolio`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-portfolio`.`projects_users_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm2-portfolio`.`projects_users_history` ;

CREATE TABLE IF NOT EXISTS `pm2-portfolio`.`projects_users_history` (
  `id_project` VARCHAR(32) NOT NULL,
  `id_user` VARCHAR(32) NOT NULL,
  `id_role` VARCHAR(5) NOT NULL DEFAULT '0',
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_project`, `id_user`, `id_role`, `start_date`),
  INDEX `fk_projects_users_users_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_projects_users_permissions_idx` (`id_role` ASC) VISIBLE,
  CONSTRAINT `fk_projects_users_history_projects`
    FOREIGN KEY (`id_project`)
    REFERENCES `pm2-portfolio`.`projects` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_users_history_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `pm2-portfolio`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_users_history_roles`
    FOREIGN KEY (`id_role`)
    REFERENCES `pm2-portfolio`.`roles` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pm2-project`.`phases`
-- -----------------------------------------------------
START TRANSACTION;
USE `pm2-project`;
INSERT INTO `pm2-project`.`phases` (`id_phase`, `code`, `name`, `description`) VALUES (0, 'initiating', 'Initiating', 'Define the desired outcomes. Create a Business Case. Define the project scope. Get the project off to a good start.');
INSERT INTO `pm2-project`.`phases` (`id_phase`, `code`, `name`, `description`) VALUES (1, 'planning', 'Planning', 'Assign the Project Core Team (PCT). Elaborate the project scope. Plan the work.');
INSERT INTO `pm2-project`.`phases` (`id_phase`, `code`, `name`, `description`) VALUES (2, 'executing', 'Executing', 'Coordinate the execution of project plans. Produce deliverables.');
INSERT INTO `pm2-project`.`phases` (`id_phase`, `code`, `name`, `description`) VALUES (3, 'closing', 'Closing', 'Coordinate formal acceptance of the project. Report on project performance. Capture Lessons Learned and post-project recommendations. Close the project administratively.');
INSERT INTO `pm2-project`.`phases` (`id_phase`, `code`, `name`, `description`) VALUES (4, 'monitorAndControl', 'Monitor & Control', 'Oversee all project work and management activities over the duration of the project: monitor project performance, measure progress, manage changes, address risks and issues, identify corrective actions etc.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pm2-portfolio`.`roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `pm2-portfolio`;
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('ATeM', 'Agile Team Member', 'Provider', 'Individual', 'Optional role', 'Team Member that focuses on producing the actual IS that is part of the project\'s solution to the stakeholders needs.', 'No', 'Agile specific role', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('APR', 'Analyst Programmer', 'Provider', 'Both', 'Optional role', 'Develops the solution according to the specifications', 'On request', 'IT specific roles', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('AGB', 'Appropriate Governance Body', 'Requestor', 'Group', 'Optional role', 'Management committee governing a number of projects, mostly at Unit or Department level', 'On request', 'Teams', 1);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('ArOw', 'Architecture Owner', 'Provider', 'Individual', 'Optional role', 'The solution architect responsible for the architecture decisions for the Project Core Team (PCT)', 'No', 'Agile specific role', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('APM', 'Assistant Project Manager', 'Provider', 'Individual', 'Optional role', 'Assists the Project Manager on project management/Administration activities', 'On request', 'Support', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('BA', 'Busines analyst', 'Provider', 'Group', 'Optional role', 'Defines the business requirements for the project', 'No', 'Operational role', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('BIG', 'Business Implementation Group', 'Requestor', 'Group', 'Key role', 'They plan and implement the business change activities.', 'On request', 'Teams', 1);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('BM', 'Business Manager ', 'Requestor', 'Individual', 'Key role', 'Acts on a daily basis on behalf of the Project Owner ', 'Key member', 'Roles', 1);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('CO', 'Consultant', 'Provider', 'Individual', 'Optional role', 'A person that can give advice regarding specific topics', 'No', 'Operational role', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('CON', 'Contractor', 'Provider', 'Group', 'Optional role', 'An external company that is contracted for a specific task(s)', 'No', 'Operational role', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('CPM', 'Contractor\'s Project Manager', 'Provider', 'Individual', 'Optional role', 'Leads the contractor\'s staff working on the project', 'On request', 'Support', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('DPC', 'Data Protection Coordinator', 'Provider', 'Individual', 'Optional role', 'Consults and advises on Data Protection aspects.', 'On request', 'Other DG Role', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('DMO', 'Document Management Officer', 'Provider', 'Individual', 'Optional role', 'Assure a coherent implementation of the Document Management Roles.', 'On request', 'Other DG Role', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('FAN', 'Functional Analyst', 'Provider', 'Individual', 'Optional role', 'Analyses and describes the requirements', 'On request', 'IT specific roles', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('FA', 'Functional Architect', 'Provider', 'Individual', 'Optional role', 'Creates the functional architecture of the solution', 'On request', 'IT specific roles', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('LAM', 'Leader of Application Mgmt', 'Provider', 'Individual', 'Optional role', 'Responsible for the delivery of the application', 'On request', 'IT specific roles', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('LSS', 'Leader of System Support', 'Provider', 'Individual', 'Optional role', 'Responsible to give support regarding system items', 'On request', 'IT specific roles', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('LISO', 'Local Information Security Officer', 'Requestor', 'Individual', 'Optional role', 'Consults and advises on Security aspects.', 'On request', 'Other DG Role', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('PrOw', 'TeamProduct Owner', 'Requestor', 'Individual', 'Optional role', 'Represents mainly client and end-users concerns', 'No', 'Agile specific role', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('PCT', 'Project Core Team ', 'Provider', 'Group', 'Key role', 'They are responsible for the implementation of the project deliverables', 'On request', 'Teams', 1);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('PM', 'Project Manager', 'Provider', 'Individual', 'Key role', 'Is responsible for the entire project and its deliverables', 'Key member', 'Roles', 1);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('PO', 'Project Owner', 'Requestor', 'Individual', 'Key role', 'The final responsible for the project', 'Chairman', 'Roles', 1);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('PQA', 'Project Quality Assurance', 'Provider', 'Both', 'Optional role', 'Responsible for quality assurance and auditing.', 'On request', 'Support', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('PSC', 'Project Steering Committee', 'Both', 'Group', 'Key decision body', 'The committee that governs the project made up of PO, BM, PM, SO', 'Yes', 'Teams', 1);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('PSO', 'Project Support Office', 'Provider', 'Group', 'Optional role', 'Offers support services to the Project Manager (PM)', 'On request', 'Support', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('PST', 'Project Support Team', 'Provider', 'Group', 'Optional role', 'They provide administrative and communications support', 'On request', 'Teams', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('RM', 'Release Manager', 'Provider', 'Individual', 'Optional role', 'Plans and supervises every release of the solution', 'On request', 'IT specific roles', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('SP', 'Solution Provider', 'Provider', 'Individual', 'Key role', 'Is responsible for providing the solution', 'Key member', 'Roles', 1);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('SU', 'Support', 'Provider', 'Group', 'Optional role', 'A group that can support the project (administation, meeting rooms, …)', 'No', 'Operational role', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('TeCo', 'Team Coordinator', 'Provider', 'Individual', 'Optional role', 'A facilitator and team coach whose main purpose is to create and maintain the conditions to allow the team to be focused on achieving specific objectives and being successful.', 'No', 'Agile specific role', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('TA', 'Technical Architect', 'Provider', 'Individual', 'Optional role', 'Creates the technical architecture of the solution', 'On request', 'IT specific roles', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('US', 'User', 'Requestor', 'Group', 'Optional role', 'The group that will use the solution', 'No', 'Operational role', 0);
INSERT INTO `pm2-portfolio`.`roles` (`id_role`, `name`, `R/P`, `G/I`, `role_type`, `description`, `PSC_participation`, `classification`, `RASCI`) VALUES ('Urs', 'User Representatives', 'Requestor', 'Both', 'Key role', 'They represent the interests of the users in the project.', 'On request', 'Operational role', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pm2-project`.`artefacts`
-- -----------------------------------------------------
START TRANSACTION;
USE `pm2-project`;
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (0, 'projectInitiationRequest', 'Project Initiation Request', 0, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (1, 'businessCase', 'Business Case', 0, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (2, 'projectCharter', 'Project Charter', 0, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (3, 'planningKickoffMeeting', 'Planning Kick-off Meeting', 1, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (4, 'projectHandbook', 'Project Handbook', 1, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (5, 'projectStakeholderMatrix', 'Project Stakeholder Matrix', 1, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (6, 'projectWorkPlan', 'Project Work Plan', 1, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (7, 'outsourcingPlan', 'Outsourcing Plan', 1, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (8, 'deliverablesAcceptancePlan', 'Deliverables Acceptance Plan', 1, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (9, 'transitionPlan', 'Transition Plan', 1, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (10, 'businessImplementationPlan', 'Business Implementation Plan', 1, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (11, 'managementPlans', 'Management Plans', 1, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (12, 'requirementsManagementPlan', 'Requirements Management Plan', 1, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (13, 'projectChangeManagementPlan', 'Project Change Management Plan', 1, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (14, 'riskManagementPlan', 'Risk Management Plan', 1, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (15, 'issueManagementPlan', 'Issue Management Plan', 1, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (16, 'qualityManagementPlan', 'Quality Management Plan', 1, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (17, 'communicationsManagementPlan', 'Communications Management Plan', 1, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (18, 'executingKickoffMeeting', 'Executing Kick-off Meeting', 2, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (19, 'projectCoordination', 'Project Coordination', 2, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (20, 'qualityAssurance', 'Quality Assurance', 2, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (21, 'projectReporting', 'Project Reporting', 2, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (22, 'informationDistribution', 'Information Distribution', 2, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (23, 'monitorProjectPerformance', 'Monitor Project Performance', 4, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (24, 'controlSchedule', 'Control Schedule', 4, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (25, 'controlCost', 'Control Cost', 4, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (26, 'manageStakeholders', 'Manage Stakeholders', 4, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (27, 'manageRequirements', 'Manage Requirements', 4, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (28, 'manageProjectChanges', 'Manage Project Changes', 4, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (29, 'manageRisks', 'Manage Risks', 4, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (30, 'manageIssuesAndDecisions', 'Manage Issues & Decisions', 4, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (31, 'manageQuality', 'Manage Quality', 4, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (32, 'manageDeliverablesAcceptance', 'Manage Deliverables Acceptance', 4, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (33, 'manageBusinessImplementation', 'Manage Business Implementation', 4, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (34, 'manageTransition', 'Manage Transition', 4, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (35, 'manageOutsourcing', 'Manage Outsourcing', 4, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (36, 'projectEndReviewMeeting', 'Project-End Review Meeting', 3, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (37, 'projectEndReport', 'Project-End Report', 3, '');
INSERT INTO `pm2-project`.`artefacts` (`id_artefact`, `code`, `name`, `id_phase`, `description`) VALUES (38, 'administrativeClosure', 'Administrative Closure', 3, '');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pm2-project`.`rasci_codes`
-- -----------------------------------------------------
START TRANSACTION;
USE `pm2-project`;
INSERT INTO `pm2-project`.`rasci_codes` (`rasci`, `name`, `description`) VALUES ('n.a.', 'Not Applicable', 'NULL');
INSERT INTO `pm2-project`.`rasci_codes` (`rasci`, `name`, `description`) VALUES ('R', 'Responsible', 'Does the work. Others can be asked to assist in a supporting role. There is just one responsible person for any given task.');
INSERT INTO `pm2-project`.`rasci_codes` (`rasci`, `name`, `description`) VALUES ('A', 'Accountable', 'Ultimately answerable for the correct and thorough completion of the work. There is just one accountable person for any given task.');
INSERT INTO `pm2-project`.`rasci_codes` (`rasci`, `name`, `description`) VALUES ('S', 'Supports', 'As part of a team, roles with a support function work with the person responsible. The support role helps complete the task.');
INSERT INTO `pm2-project`.`rasci_codes` (`rasci`, `name`, `description`) VALUES ('C', 'Consulted', 'Those whose opinions are requested and with whom there is two-way communication. The consulted role does not help complete the task.');
INSERT INTO `pm2-project`.`rasci_codes` (`rasci`, `name`, `description`) VALUES ('I', 'Informed', 'Those who are kept informed of progress.');
INSERT INTO `pm2-project`.`rasci_codes` (`rasci`, `name`, `description`) VALUES ('A/S', 'Accountable/Supports', 'NULL');
INSERT INTO `pm2-project`.`rasci_codes` (`rasci`, `name`, `description`) VALUES ('S/C', 'Supports/Consulted', 'NULL');
INSERT INTO `pm2-project`.`rasci_codes` (`rasci`, `name`, `description`) VALUES ('I/C', 'Informed/Consulted', 'NULL');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pm2-project`.`rasci`
-- -----------------------------------------------------
START TRANSACTION;
USE `pm2-project`;
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (0, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (0, 'PSC', 'n.a.');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (0, 'PO', 'A/S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (0, 'BM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (0, 'BIG', 'S/C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (0, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (0, 'PM', 'n.a.');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (0, 'PCT', 'n.a.');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (1, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (1, 'PSC', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (1, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (1, 'BM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (1, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (1, 'SP', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (1, 'PM', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (1, 'PCT', 'n.a.');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (2, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (2, 'PSC', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (2, 'PO', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (2, 'BM', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (2, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (2, 'SP', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (2, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (2, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (3, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (3, 'PSC', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (3, 'PO', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (3, 'BM', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (3, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (3, 'SP', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (3, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (3, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (4, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (4, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (4, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (4, 'BM', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (4, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (4, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (4, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (4, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (5, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (5, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (5, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (5, 'BM', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (5, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (5, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (5, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (5, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (6, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (6, 'PSC', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (6, 'PO', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (6, 'BM', 'S/C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (6, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (6, 'SP', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (6, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (6, 'PCT', 'S/C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (7, 'AGB', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (7, 'PSC', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (7, 'PO', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (7, 'BM', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (7, 'BIG', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (7, 'SP', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (7, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (7, 'PCT', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (8, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (8, 'PSC', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (8, 'PO', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (8, 'BM', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (8, 'BIG', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (8, 'SP', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (8, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (8, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (9, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (9, 'PSC', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (9, 'PO', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (9, 'BM', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (9, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (9, 'SP', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (9, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (9, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (10, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (10, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (10, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (10, 'BM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (10, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (10, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (10, 'PM', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (10, 'PCT', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (12, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (12, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (12, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (12, 'BM', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (12, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (12, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (12, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (12, 'PCT', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (13, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (13, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (13, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (13, 'BM', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (13, 'BIG', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (13, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (13, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (13, 'PCT', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (14, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (14, 'PSC', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (14, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (14, 'BM', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (14, 'BIG', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (14, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (14, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (14, 'PCT', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (15, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (15, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (15, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (15, 'BM', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (15, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (15, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (15, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (15, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (16, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (16, 'PSC', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (16, 'PO', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (16, 'BM', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (16, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (16, 'SP', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (16, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (16, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (17, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (17, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (17, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (17, 'BM', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (17, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (17, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (17, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (17, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (18, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (18, 'PSC', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (18, 'PO', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (18, 'BM', 'S/C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (18, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (18, 'SP', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (18, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (18, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (19, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (19, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (19, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (19, 'BM', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (19, 'BIG', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (19, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (19, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (19, 'PCT', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (20, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (20, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (20, 'PO', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (20, 'BM', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (20, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (20, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (20, 'PM', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (20, 'PCT', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (21, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (21, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (21, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (21, 'BM', 'S/C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (21, 'BIG', 'I/C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (21, 'SP', 'I/C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (21, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (21, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (22, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (22, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (22, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (22, 'BM', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (22, 'BIG', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (22, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (22, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (22, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (23, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (23, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (23, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (23, 'BM', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (23, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (23, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (23, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (23, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (24, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (24, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (24, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (24, 'BM', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (24, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (24, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (24, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (24, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (25, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (25, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (25, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (25, 'BM', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (25, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (25, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (25, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (25, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (26, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (26, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (26, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (26, 'BM', 'S/C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (26, 'BIG', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (26, 'SP', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (26, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (26, 'PCT', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (27, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (27, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (27, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (27, 'BM', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (27, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (27, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (27, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (27, 'PCT', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (28, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (28, 'PSC', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (28, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (28, 'BM', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (28, 'BIG', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (28, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (28, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (28, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (29, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (29, 'PSC', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (29, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (29, 'BM', 'S/C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (29, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (29, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (29, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (29, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (30, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (30, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (30, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (30, 'BM', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (30, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (30, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (30, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (30, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (31, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (31, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (31, 'PO', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (31, 'BM', 'S/C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (31, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (31, 'SP', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (31, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (31, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (32, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (32, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (32, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (32, 'BM', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (32, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (32, 'SP', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (32, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (32, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (33, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (33, 'PSC', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (33, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (33, 'BM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (33, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (33, 'SP', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (33, 'PM', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (33, 'PCT', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (34, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (34, 'PSC', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (34, 'PO', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (34, 'BM', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (34, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (34, 'SP', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (34, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (34, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (35, 'AGB', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (35, 'PSC', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (35, 'PO', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (35, 'BM', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (35, 'BIG', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (35, 'SP', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (35, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (35, 'PCT', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (36, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (36, 'PSC', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (36, 'PO', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (36, 'BM', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (36, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (36, 'SP', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (36, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (36, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (37, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (37, 'PSC', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (37, 'PO', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (37, 'BM', 'S');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (37, 'BIG', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (37, 'SP', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (37, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (37, 'PCT', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (38, 'AGB', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (38, 'PSC', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (38, 'PO', 'A');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (38, 'BM', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (38, 'BIG', 'I');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (38, 'SP', 'C');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (38, 'PM', 'R');
INSERT INTO `pm2-project`.`rasci` (`id_artefact`, `id_role`, `rasci`) VALUES (38, 'PCT', 'I');

COMMIT;

