-- MySQL Script generated by MySQL Workbench
-- Thu Feb  4 20:23:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pm2-project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pm2-project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pm2-project` DEFAULT CHARACTER SET utf8 ;
USE `pm2-project` ;

-- -----------------------------------------------------
-- Table `pm2-project`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm2-project`.`projects` (
  `id_project` INT GENERATED ALWAYS AS (),
  `name` VARCHAR(100) NOT NULL,
  `code` VARCHAR(20) NOT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id_project`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-project`.`phases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm2-project`.`phases` (
  `id_phase` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id_phase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-project`.`projects_phases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm2-project`.`projects_phases` (
  `id_project` INT NOT NULL,
  `id_phase` INT NOT NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `duration` INT NULL COMMENT 'in days',
  PRIMARY KEY (`id_project`, `id_phase`),
  CONSTRAINT `fk_projects_phases_projects`
    FOREIGN KEY (`id_project`)
    REFERENCES `pm2-project`.`projects` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_phases_phases`
    FOREIGN KEY (`id_phase`)
    REFERENCES `pm2-project`.`phases` (`id_phase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_projects_phases_phases_idx` ON `pm2-project`.`projects_phases` (`id_phase` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pm2-project`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm2-project`.`users` (
  `id_user` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-project`.`stakeholders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm2-project`.`stakeholders` (
  `id_stakeholder` INT NOT NULL COMMENT 'Strakeholders are people (or groups) who can affect or be affected by the activities carried out during a project’s lifecycle and/or by the project’s output(s) and outcome(s). A stakeholder can exert influence over the project and its deliverables.',
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_stakeholder`),
  CONSTRAINT `fk_stakeholders_users`
    FOREIGN KEY (`id_stakeholder`)
    REFERENCES `pm2-project`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-project`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm2-project`.`teams` (
  `id_team` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `code` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_team`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-project`.`impacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm2-project`.`impacts` (
  `id_impact` INT NOT NULL,
  `value` VARCHAR(1) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_impact`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm2-project`.`stakeholders_teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm2-project`.`stakeholders_teams` (
  `id_stakeholder` INT NOT NULL,
  `id_team` INT NOT NULL,
  `id_impact` INT NOT NULL,
  PRIMARY KEY (`id_stakeholder`, `id_team`, `id_impact`),
  CONSTRAINT `fk_stakeholders_teams_stakeholders`
    FOREIGN KEY (`id_stakeholder`)
    REFERENCES `pm2-project`.`stakeholders` (`id_stakeholder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stakeholders_teams_teams`
    FOREIGN KEY (`id_team`)
    REFERENCES `pm2-project`.`teams` (`id_team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stakeholders_teams_impacts`
    FOREIGN KEY (`id_impact`)
    REFERENCES `pm2-project`.`impacts` (`id_impact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_stakeholders_teams_teams_idx` ON `pm2-project`.`stakeholders_teams` (`id_team` ASC) VISIBLE;

CREATE INDEX `fk_stakeholders_teams_impacts_idx` ON `pm2-project`.`stakeholders_teams` (`id_impact` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
